# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


development:
  email_provider_username: <%= ENV["MAHONEY_GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["MAHONEY_GMAIL_PASSWORD"] %>
  mailchimp_api_key: <%= ENV["MAHONEY_MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAHONEY_MAILCHIMP_LIST_ID"] %>
  domain_name: example.com
  owner_email: <%= ENV["MAHONEY_OWNER_EMAIL"] %>
  secret_key_base: 95dbae6b2900769e18e544eb05bbf32563e251aa651f9d2072d28f134fd86affec818d762a146190e3c74ac1100af9e1cb898975b410f84a6f450179132a8a89

test:
  secret_key_base: ad7aef1b1a2cc30841215ca24958654fdbb6a1acd7cd06ba89ba1b8db74cc16cb9109c80d61a10bf29019e3de474da2259ed7144579f956afd807469dbb89ecc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["MAHONEY_GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["MAHONEY_GMAIL_PASSWORD"] %>
  mailchimp_api_key: <%= ENV["MAHONEY_MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAHONEY_MAILCHIMP_LIST_ID"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  owner_email: <%= ENV["MAHONEY_OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
